### ISSUE TITLE
Unable to move camera on map RUMBLE

### ISSUE THREAD

**Issue by DummkopfOfHachtenduden** [TalonBraveInfo/OpenHoW#108]
Camera can not be moved on map `RUMBLE` with neither keyboard nor controller.

**Comment by hogsy** [comment]
Tracked this down yesterday. This is basically because it's failing to grab an actor on that map to possess, because we're only checking for one type of actor.

I'm in the process of adding a proper collection per-team etc. which should rectify this though it's going to take a little bit of time as I need to implement systems which don't currently exist.
