### ISSUE TITLE
Convert POG to Json during extraction process

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/OpenHoW#113]
~Unsure if this will go into .map blob or into it's own blob.~ 

This will go into it's own blob under the given map directory, e.g. `mymap/mymap.actors`

**Comment by BALIST0N** [comment]
hi ! i created a console window app who can respond to this enhancement,
 created in c# with Core .net 3.1 (compatible with linux and mac)

https://github.com/BALIST0N/Pog_To_Json/tree/master

i'm not very sure about exported format and values converted, i try to respect some infos from the repo and a reference on Skybreaker forums, since the code is easily adaptable i'm will be here to maintain my contribution 
🥇

**Comment by hogsy** [comment]
Hi @BALIST0N we would need this functionality introduced into the [extractor](https://github.com/TalonBraveInfo/OpenHoW/tree/master/src/tools/extractor) itself. I would suggest forking the repository and implementing your changes that way.

If you're unsure of the formatting or anything like that, feel free to throw me a DM on Discord.
