### ISSUE TITLE
Networking implementation

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/OpenHoW#21]
We could probably use [SDL2_net](https://www.libsdl.org/projects/SDL_net/) - should implement this into the Launcher.

[Floating point determinism](https://gafferongames.com/post/floating_point_determinism/)
[A Tale of De syncs](https://blog.forrestthewoods.com/synchronous-rts-engines-and-a-tale-of-desyncs-9d8c3e48b2be)

**Comment by hogsy** [comment]
@solemnwarning if you decide to roll your own layer instead of using SDL_Net for example, would you mind implementing it as part of the platform library and then OpenHoW can interface via that?

Thanks!

**Comment by solemnwarning** [comment]
I think I'm going to break this into a series of mini-milestones to make it more approachable, something like:

1) Spectate-only network play - existing game mode with clients entirely slaved to the host simulation by synchronising actor properties.

2) Independent simulation - Clients run their own simulation, with periodic re-sync to the server's properties, still running off the server's clock with a pulse sent every tick.

3) Clock synchronisation - Clients now maintain their own clock, with a periodic pulse from the server used for adjustment.

4) Actual multiplayer - Clients can move their pig on their turn. The active client becomes responsible for the clock so that it can do things like creating/destroying actors without having to wait for the server to process it and reply.

5) Proper game start/end, lobby, UI, etc
